### PR TITLE
Prune stale HTTPRoutes when tags are removed from Ingress rules

### LINKED ISSUE #895: HTTPRoute remains after removing tags from Knative Service traffic
- Summary: Removing tags from a Knative Service traffic block does not delete the corresponding HTTPRoute; stale routes remain after reconciliation.
- Expected: Owned HTTPRoutes no longer referenced by current traffic tags are pruned on reconciliation.
- Actual: Tag-specific HTTPRoutes (e.g., okay-<svc>.<ns>...) remain until manually deleted.

Steps to Reproduce:
1) Create a Knative Service with traffic entries that include tagged routes (e.g., tag: okay, tag: canary).
2) Wait for reconciliation; tag-specific HTTPRoutes are created.
3) Edit the Service to remove one or more tags from the traffic spec (revisions unchanged).
4) Observe after reconciliation that the corresponding tag HTTPRoutes are not deleted.

Impact:
- Stale routing config persists (unexpected hosts/routes remain) until manual deletion.

Workaround:
- Manually delete the stale HTTPRoutes.

### PR DESCRIPTION
**Pull request by kahirokunn**
- Add pruning in reconcileIngress to delete owned HTTPRoutes not referenced
- Add unit test to verify stale route deletion behavior

/kind bug

Fixes #895

Release Note:
```release-note
Fix a bug where HTTPRoutes could remain after tags were removed. Stale routes are now deleted during reconciliation.
```

### CODE REVIEW

**Comment by kahirokunn** [comment]
@dprotaso Hello! I'd be grateful if you could leave a review when you have a moment! 🙏

**Comment by kahirokunn** [comment]
@dprotaso Hello 🤚

File: pkg/reconciler/ingress/ingress.go [hunk 1]
```diff
@@ -123,6 +129,26 @@ func (c *Reconciler) reconcileIngress(ctx context.Context, ing *v1alpha1.Ingress
...
+	{
+		existingRoutes, err := c.httprouteLister.HTTPRoutes(ing.Namespace).List(labels.Everything())
+		if err != nil {
+			return fmt.Errorf("failed to list HTTPRoutes: %w", err)
+		}
+		for _, r := range existingRoutes {
+			// Don't touch routes not owned by this Ingress
+			if !metav1.IsControlledBy(r, ing) {
+				continue
+			}
```
Comment (dprotaso) [inline pkg/reconciler/ingress/ingress.go]: With the label mentioned above we can drop this

**Review by dprotaso — COMMENTED** [review]
Change looks great - thanks for finding the bug.

Just looking for a minor tweak

File: pkg/reconciler/ingress/ingress.go [hunk 2]
```diff
@@ -123,6 +129,26 @@ func (c *Reconciler) reconcileIngress(ctx context.Context, ing *v1alpha1.Ingress
 		}
 	}
 
+	// Delete HTTPRoutes that don't exist in the current Spec (i.e., tags removed and no longer referenced)
+	{
+		existingRoutes, err := c.httprouteLister.HTTPRoutes(ing.Namespace).List(labels.Everything())
```
[the remark this answers is not in the document]
Comment (kahirokunn) [reply pkg/reconciler/ingress/ingress.go]: Thx. fixed.

**Comment by kahirokunn** [comment]
@dprotaso I've addressed all the points you raised. When you have a moment, I would appreciate it if you could take another look 🙏

File: pkg/reconciler/ingress/resources/httproute.go [hunk 3]
```diff
@@ -204,6 +204,7 @@ func MakeHTTPRoute(
 			Name:      LongestHost(rule.Hosts),
 			Namespace: ing.Namespace,
 			Labels: kmeta.UnionMaps(ing.Labels, map[string]string{
+				networking.IngressLabelKey:    ing.Name,
```
Comment (dprotaso) [inline pkg/reconciler/ingress/resources/httproute.go]: I wonder why our tests were passing before without this label lol

**Comment by kahirokunn** [comment]
@dprotaso I've addressed all the points you raised. All tests have been passed. When you have a moment, I would appreciate it if you could take another look 🙏

**Comment by dprotaso** [comment]
thanks @kahirokunn 🎉
